version: '3'

services:
  db:
    image: postgres
    ports:
      - 5430:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: devops
    volumes:
      - ./db/data:/var/lib/postgresql/data
  backend:
    build: ./backend
    environment:
      NODE_ENV: production
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: devops
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - 5000:5000
    depends_on:
      - db
    links:
      - db  
  frontend:
    restart: on-failure
    build: ./frontend
    expose:
      - 3000
  nginx:
    image: nginx
    volumes:
      - ./nginx/node.conf:/etc/nginx/conf.d/node.template
    ports:
      - '8080:80'
    command: 'bash -c "cat /etc/nginx/conf.d/node.template > /etc/nginx/conf.d/default.conf && nginx -g ''daemon off;''"'